export const defColumns = [
    {   id: 1,
        name: "id",
        label: "#",
        format: (value) => value,
        flex: "2",
        justifyContent: "flex-start",
    },
    {   id: 2,
        name: "date",
        label: "Дата",
        format: (value) => value.toLocaleDateString("ru-RU", {year: 'numeric', month: '2-digit', day: '2-digit', hour12: false, hour:'2-digit', minute:'2-digit', second:'2-digit'}),
        flex: "4",
        justifyContent: "flex-start",
    },
    {   id: 3,
        name: "status",
        label: "Статус",
        format: (value) => value,
        flex: "2",
        justifyContent: "flex-start",
    },
    {   id: 4,
        name: "count",
        label: "Позиций",
        format: (value) => value,
        flex: "2",
        justifyContent: "center",
    },
    {   id: 5,
        name: "summa",
        label: "Сумма",
        format: (value) => new Intl.NumberFormat("ru-RU", {style: 'currency', currency: 'RUB'}).format(value),
        flex: "3",
        justifyContent: "flex-end",
    },
    {   id: 6,
        name: "bayer",
        label: "ФИО покупателя",
        format: (value) => value,
        flex: "9",
        justifyContent: "flex-start",
    }
];