export const defColumns = [
    {   id: 1,
        name: "id",
        label: "#",
        flex: "2",
    },
    {   id: 2,
        name: "date",
        label: "Дата",
        flex: "3",
    },
    {   id: 3,
        name: "status",
        label: "Статус",
        flex: "4",
    },
    {   id: 4,
        name: "count",
        label: "Позиций",
        flex: "2",
    },
    {   id: 5,
        name: "summa",
        label: "Сумма",
        flex: "3",
    },
    {   id: 6,
        name: "bayer",
        label: "ФИО покупателя",
        flex: "8",
    }
];